language: ruby
rvm: 2.3.3
cache:
  bundler: true
  directories:
  - node_modules
branches:
  only:
  - master
before_install:
- nvm install 7.4.0
install:
- npm install
- bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
before_script:
- git config --global user.name "hnbot"
- git config --global user.email "nygrenh+hnbot@gmail.com"
- export COMMIT_MESSAGE=Update:\ $(git log -1 --pretty=%s)
- git clone -b gh-pages --single-branch https://github.com/materiaalit/ohjelmointi-s18.git
  build
script:
- bundle exec middleman build
after_success:
- cd build
- git checkout HEAD README.md
- git checkout HEAD CNAME
- git add --all
- git commit -m "$COMMIT_MESSAGE"
- git push "https://hnbot:$GITHUB_API_KEY@github.com/materiaalit/ohjelmointi-s18.git"
  gh-pages:gh-pages 2>&1 | sed "s/$GITHUB_API_KEY/<confidential>/g"
env:
  global:
    secure: OFDBtHE4i3hTcXaDt0NGfdzqxCSV2Z5F+UKbJpqmfqWrdhrSsNO30SQqAGsxiLji0KZhNoNHbtNXoUKRY5y4wC6lXbetTc7rt2ZrjrYeLXbqryAY166CuYy08mIk/505iciHGPCAW8CVH+p9mWGJg/ED9iWWFybA6kkEf/603kgd5o6wZWyYmg21fJuFJITidB+dCaaqPEwOg504X+iCz0jR1UxT4YX2kD+MdolkrHJ98xhKZkjltQBBBKsMPv9/n572efeezb7GeUvpnngjgtC6lnNJlsEsPnKSpIR/Qs0nMGb8TURcdWtI2wOtPn+qKwBeMDk54XpxPNGi+LsdtgfAZQiJ2GPv1D7UolafAwcRBLWMEGkV25FinYfimPWxivkxNqax4xp7lQUloy34jRS7kyJNVp5NOIZAynsPrm3P2y1ZPJZ5pR3jhXKaBPDt3ysEmrT8ZjgMwokOCuSDR8u8/1sPCplnjqqPikEF+CEOwhRZbiphKo8e9bq63N9V2M8o7qdNu0bl+GzExGosJ5LPC17WYlSzqoYx+LyYgkkY5TbXuyhonwfDT7rh18q1/yV2SKsthutqwSxSMuYiau88BpRnuMUb2I1YCGim5GQu3Lxnb1h5Lxi5w9+DT+DDXePkQzR97RCJByml/LOFTsW9AwGMMWput+gJbpA7MJs=
